// <auto-generated />
namespace IsmIoTPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addpasswordfordeviceusedduringprovisioning : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addpasswordfordeviceusedduringprovisioning));
        
        string IMigrationMetadata.Id
        {
            get { return "201612130914059_Add password for device used during provisioning."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
