// <auto-generated />
namespace IsmIoTPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RenameReleaseField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameReleaseField));
        
        string IMigrationMetadata.Id
        {
            get { return "201702100852555_Rename Release Field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
